apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  spring.datasource.username: dGVzdGRi  # Base64 encoded value of 'testdb'
  spring.datasource.password: eW91cl9wYXNzd29yZA==  # Base64 encoded value of 'your_password'
